### ISSUE TITLE
[BUG] E06: Basic Object Tracking,When running  track_and_move.py

### ISSUE THREAD

**Issue by zjuxlx** [generalized-intelligence/GAAS#53] opened 2019-09-04 02:26 UTC
## Context
My relevant information about my setup.

* ROS: [Kinetic]
* Gazebo: [7.15.0]
* Ubuntu: [16.04]
* System Platform: [X86]
* Python: [2.7.12]

## Current Behavior
Autonomous Drone Software E06: Basic Object Tracking

1.

When python track_and_move.py It occurs this question:
Traceback (most recent call last):
  File "track_and_move.py", line 134, in <module>
    SimpleTrackAndMove(resolution, K,left_topic=left_topic, right_topic=right_topic, object_position_topic=object_position_topic)
TypeError: __init__() takes at least 4 arguments (6 given)
![Screenshot from 2019-09-04 10-17-38](https://user-images.githubusercontent.com/43372465/64220806-40293180-cefd-11e9-935e-1a625758bb55.png)
The source code is:
![Screenshot from 2019-09-04 10-19-25](https://user-images.githubusercontent.com/43372465/64220893-89798100-cefd-11e9-98ff-963eea6046db.png)
![Screenshot from 2019-09-04 10-19-40](https://user-images.githubusercontent.com/43372465/64220904-9302e900-cefd-11e9-9ade-28424add34a1.png)

2.

When I delete commander in def __init__(),
![Screenshot from 2019-09-04 10-21-40](https://user-images.githubusercontent.com/43372465/64220981-ce9db300-cefd-11e9-8caa-f2c8fd314843.png)
It occurs this question:
![Screenshot from 2019-09-04 10-22-17](https://user-images.githubusercontent.com/43372465/64221002-e37a4680-cefd-11e9-9011-07264f01628b.png)

3.

And if I  add commander in the main function,
![Screenshot from 2019-09-04 10-24-34](https://user-images.githubusercontent.com/43372465/64221083-3653fe00-cefe-11e9-87e8-31f5aba40b20.png)

It occurs this question:
![Screenshot from 2019-09-04 10-25-11](https://user-images.githubusercontent.com/43372465/64221112-4d92eb80-cefe-11e9-960f-429944b10498.png)

**Comment by metaphox** [comment] 2019-09-04 11:23
Please try the following:

1. remove the whole line 126 from `track_and_move.py`, i.e. remove `rospy.init_node('track_and_move', anonymous=True)`, since the `Commander` class will call `init_node` on its own.
2. remove the `commander` argument from the `SimpleTrackAndMove` call on line 134.

**Comment by zjuxlx** [comment] 2019-09-05 03:54
Thanks for your reply.
I made a success after making this following changes in track_and_move.py
1. remove the commander argument from the def __inti__() on line 20.
2. remove the whole line 126.
3. remove the commander argument frome the SimpleTrackAndMove call on line 134.

**Comment by ninawrong** [comment] 2019-09-05 06:20
Issue closed as the problem is solved

**Closed by ninawrong** 2019-09-05 06:20 UTC
Labels: Tutorial, good first issue
